# Code Quality Workflow
#
# This workflow ensures code quality and consistency across the codebase.
# It runs on every push to master and on pull request events (opened, updated, reopened).
#
# What it checks:
# 1. Linting - Ensures code follows style guidelines and catches potential issues
# 2. Formatting - Verifies code is properly formatted using Prettier
# 3. Code style consistency - Maintains uniform code style across the project
#
# This helps maintain clean, readable, and consistent code that follows best practices.

name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install Yarn
        run: corepack enable

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run linting
        run: yarn lint

      - name: Check formatting
        run: yarn prettier --check "**/*.{ts,js,yml}"
