# Dependency Updates Workflow
#
# This workflow automatically updates dependencies to keep the project secure and up-to-date.
# It runs every day at 9 AM UTC and can also be triggered manually.
#
# What it does:
# 1. Checks for outdated npm dependencies
# 2. Updates them to the latest versions
# 3. Runs tests to ensure nothing breaks after updates
# 4. Creates a pull request with the changes if tests pass
# 5. Includes detailed PR description with what was updated
#
# This helps maintain security and ensures the project uses the latest stable versions.

name: Dependency Updates

on:
  schedule:
    # Run every day at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    
    - name: Check for outdated dependencies
      run: yarn outdated || true
    
    - name: Update dependencies
      run: |
        yarn upgrade-interactive --latest
        yarn install
      continue-on-error: true
    
    - name: Run tests after updates
      run: yarn test
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore(deps): update dependencies'
        title: 'chore(deps): update dependencies'
        body: |
          ## 🤖 Automated Dependency Updates
          
          This PR updates dependencies to their latest versions.
          
          ### Changes:
          - Updated development dependencies
          - Updated production dependencies
          
          ### Testing:
          - ✅ All tests pass
          - ✅ Build successful
          
          Please review the changes and merge if everything looks good.
        branch: chore/update-dependencies
        delete-branch: true 